dist: trusty
language: node_js
node_js:
  - "10"
addons:
  apt:
    packages:
      - dpkg
  chrome: stable
  mariadb: '10.5'

install: mysql -e "SET Password=PASSWORD('travis')"

before_script:
  # setup database
  - sudo mysql -u root < warrantyDB.sql
  # build express application and serve it
  - npm install & npm run start &
  # give background tasks some time to start up
  - sleep 15
  # travis now automatically runs `npm run test`

