dist: trusty
language: node_js
node_js:
  - "10"
addons:
  apt:
    packages:
      - dpkg
  chrome: stable
  mariadb: '10.5'
before_script:
  # setup database
  - sudo mysql -u root < ./database/warrantyDB.sql
  # build express application and serve it
  - npm install & npm run start &
  # give background tasks some time to start up
  - sleep 10
  # travis now automatically runs `npm run test`

